version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: conteneurfront
   networks:
    -  mern
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   build:
      context: ./api
      dockerfile: Dockerfile
   ports:
     - 3080:3080
   container_name: conteneurbackend
   networks:
     - mern
   volumes:
    - ./api/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: conteneurmongo
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
